language: node_js
node_js: 9
script:
  - npm run lint
  - npm test
after_success:
 - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
cache:
  directories:
    - node_modules